steps:
  - label: ":lint-roller: fmtcheck"
    env:
      SEGMENT_BUILDKITE_IMAGE: 'buildkite-agent-golang1.14'
    agents:
      queue: v1
    commands: |
      make fmt
    plugins:
      - docker#v3.3.0:
          image: hashicorp/terraform:0.12.16

  - label: ":lint-roller: Lint"
    env:
      SEGMENT_BUILDKITE_IMAGE: 'buildkite-agent-golang1.14'
    agents:
      queue: v1
    commands: |
      make lint
    plugins:
      - docker#v3.3.0:
          image: wata727/tflint:0.12.1
