steps:
  - label: ":lint-roller: fmtcheck"
    env:
      SEGMENT_BUILDKITE_IMAGE: 'buildkite-agent-golang1.14'
    agents:
      queue: v1
    commands: |
      make fmtchk
  - label: ":lint-roller: Lint"
    env:
      SEGMENT_BUILDKITE_IMAGE: 'buildkite-agent-golang1.14'
    agents:
      queue: v1
    commands: |
      make lint

